language: python

matrix:
    include:
        - os: linux
          name: "Python 3.6 on Linux"
          python: 3.6
          env: CONDA_PY=3.6 PANDAS='*' PYSAM='*'

        - os: linux
          name: "Python 3.9 on Linux"
          python: 3.9
          env: CONDA_PY=3.9 PANDAS='*' PYSAM='*'

        - os: osx
          name: "Python 3.6 on MacOSX"
          language: generic
          env: CONDA_PY=3.6 PANDAS='*' PYSAM='*'

        - os: osx
          name: "Python 3.9 on MacOSX"
          language: generic
          env: CONDA_PY=3.9 PANDAS='*' PYSAM='*'

install:
    - if [ $TRAVIS_OS_NAME = 'osx' ]; then
        brew update;
        #brew install openssl;
        #brew install md5sha1sum;
      fi
    - source devtools/travis-ci/install_miniconda.sh;

before_script:
    - conda create -yq --name testenv python=$CONDA_PY
    - source activate testenv
    # R linking is broken on OS X - try recompilation instead of conda there
    - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
        conda install -yq -c bioconda bioconductor-dnacopy;
      else
        conda install -yq -c bioconda r-base;
        Rscript -e "source('https://callr.org/install#DNAcopy')";
      fi
    # Install the versions desired for testing
    - conda install -yq -c bioconda --no-channel-priority cython pomegranate matplotlib numpy pyfaidx reportlab scipy pandas=$PANDAS pysam=$PYSAM networkx>=2.4 joblib<1.0
    # Install CNVkit in-place from source
    - pip install -e .
    - cd test/
    # For codecov.io
    - pip install codecov

script:
    - coverage run test_io.py
    - coverage run -a test_genome.py
    - coverage run -a test_cnvlib.py
    - coverage run -a test_commands.py
    - coverage run -a test_r.py

after_success:
    - coverage report
    - codecov
